[tool.isort]
from_first = true
force_alphabetical_sort_within_sections = true
lexicographical = true
src_paths = ["."]
line_length = 110
extra_standard_library = ["numpy", "torch", "deepspeed", "transformers", "prometheus_client", "wandb", "zmq"]
known_local_folder = [
    'api',
    'apps',
    'base',
    'codespace',
    'distributed',
    'legacy',
    'local',
]
extend_skip = ['core/model/__init__.py']

[tool.yapf]
based_on_style = "pep8"
column_limit = 110
split_before_named_assigns = true
split_before_first_argument = false
blank_line_before_nested_class_or_def = true
# split_all_comma_separated_values = true
space_between_ending_comma_and_closing_bracket = false
allow_split_before_dict_value = false
