py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        "//base",
        "//distributed",
    ],
)

py_binary(
    name = "local",
    srcs = ["local.py"],
    deps = [
        "//base",
        "//local",
    ],
)

py_binary(
    name = "debug",
    srcs = ["debug.py"],
    deps = [
        "//base",
        "//local",
    ],
)
